### ISSUE TITLE
Include different parameter types?

### ISSUE THREAD

**Issue by djarran** [catalyst/moodle-tool_wsformat#28]
The API Documentation that Moodle provides at `admin/webservice/documentation.php` breaks down parameters into three types (string, int, double). The code uses the following switch statement below. So any other parameter types such as boolean (0 or 1), or the difference between alpha, alphanum, alphaext, text, and theme types is lost and listed as a general `string` type.

`Line 613 - moodle/webservice/renderer.php`
```php
switch ($paramdescription->type) {
        case PARAM_BOOL: // 0 or 1 only for now
        case PARAM_INT:
            $type = 'int';
            break;
        case PARAM_FLOAT;
            $type = 'double';
            break;
        default:
            $type = 'string';
}
```

Did you want us to check for these other parameter types and include them in the cURL parameterised values or in the description of each parameter in the Postman request like below, or keep it the same as the documentation?

<img width="1115" alt="Screenshot 2023-09-20 at 10 21 53 am" src="https://github.com/catalyst/moodle-tool_wsformat/assets/65814885/6cced299-da6d-48d0-9802-b426a9861c15">

- [ ] #7 Test

**Comment by djarran** [comment]
Use the same types as the documentation

**Comment by ZachPregl** [comment]
N/a
