### ISSUE TITLE
Move strings into language strings

### ISSUE THREAD

**Issue by djarran** [catalyst/moodle-tool_wsformat#34]
- Currently there are many strings that are not defined using the Strings API.
- To submit to the Moodle Plugin Directory, one of the requirements (as described in Moodle's [Plugin Contribution](https://moodledev.io/general/community/plugincontribution#sharing-code-in-the-plugins-directory) and [Plugin Tutorial](https://docs.moodle.org/dev/Tutorial) pages) is ensuring that strings can easily be translated to multiple languages.

These strings should be defined in `lang/en/tool_wsformat.php`
```php
$string['pluginname'] = 'Format Webservices';
$string['plugindescription'] = 'This plugin displays all web services available within Moodle and the respective formatted requests to help developers better understand the communication between their Moodle site and external applications or services';
```

And can be used in Mustache templates like so:
```html
<h2>{{#str}} pluginname, tool_wsformat {{/str}}</h2>
<p>{{#str}} plugindescription, tool_wsformat {{/str}}</p>
```

Or in PHP (see [Strings API](https://docs.moodle.org/dev/String_API#get_string.28.29)):
```php
get_string('pluginname', 'tool_wsformat');
```

A good example is the plugin in `/tool/admin/templatelibrary`

**Comment by ZachPregl** [comment]
Completed in dev2
